import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header.jsx"
import { Providers } from "./GlobalRedux/Provider";
// import { persistor } from "./GlobalRedux/store";
// import { PersistGate } from "redux-persist/integration/react";
// import { persistor } from './store';
// import store from "./GlobalRedux/store";
// import { Provider } from "react-redux";
import { PersistGateways } from "./GlobalRedux/PersistGateways";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="m-0">
      
        <body className={`${inter.className} m-0`}>
          <ClerkProvider afterSignOutUrl={process.env.NEXT_PUBLIC_AFTER_SIGN_OUT_URL}>
            <Header/>
            <Providers>
              <PersistGateways>
                {children}
              </PersistGateways>
            </Providers>
            </ClerkProvider></body>
      
    </html>
  );
}
